# declare base image
FROM ubuntu

# run commands for initialize container with minimal configuration
RUN apt-get update

# Copy local content to the container
COPY <local path> <container path>

# run anything extra needed

# Declare entry points
ENTRYPOINT [ "executable" ]